// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:ac12a39e-81b3-410a-a4e8-3f9555ee5141",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_zqOH9lt6B",
    "aws_user_pools_web_client_id": "25o2g52vi9nd51ira6heov4jdq",
    "oauth": {
        "domain": "ra2-serverless-master.auth.ap-southeast-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://ra2.sonabstudios.com/",
        "redirectSignOut": "https://ra2.sonabstudios.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
