// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:bbcaf30d-4cae-4de6-a199-cc0e59e9b745",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_iJvX9R7RV",
    "aws_user_pools_web_client_id": "23dh4b2jv56qoovs13ga8vqjre",
    "oauth": {
        "domain": "ra2-serverless-dev.auth.ap-southeast-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/,https://ra2-serverless-dev.auth.ap-southeast-1.amazoncognito.com/",
        "redirectSignOut": "https://ra2-dev.sonabstudios.com/,http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS"
};


export default awsmobile;
