// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:2ee3e3bc-2d27-4a9d-84ec-016fbbe894ad",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_IvZR0Eriv",
    "aws_user_pools_web_client_id": "64pt4ahbdrlke17jtq9cu3hgig",
    "oauth": {
        "domain": "ra2-serverless-dev.auth.ap-southeast-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://ra2-dev.sonabstudios.com/",
        "redirectSignOut": "https://ra2-dev.sonabstudios.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
